version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      svelte:
        patterns:
          - svelte
          - "@sveltejs/*"
      testing:
        patterns:
          - "@playwright/*"
          - "@axe-core/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
